/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/dashboard/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard KPI cards for the selected period versus the previous one. */
        get: operations["GetKpis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/managers/ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Managers ranked by gross profit or average check for the selected period. */
        get: operations["GetManagerRanking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Revenue, gross profit and Paid sales count over time, bucketed by a server-chosen step. */
        get: operations["GetTimeseries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Revenue, profit, margin, units and revenue share per product category. */
        get: operations["GetCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/products/top": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The 10 products with the highest gross profit for the selected period. */
        get: operations["GetTopProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/sales/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Keyset-paginated feed of recent sales (all statuses) for the selected period. */
        get: operations["GetRecentSales"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AverageCheckMetric: {
            /** Format: double */
            current: null | number | string;
            /** Format: double */
            previous: null | number | string;
            /** Format: double */
            change: null | number | string;
        };
        BestManagerDto: {
            /** Format: uuid */
            managerId: string;
            firstName: string;
            lastName: string;
            /** Format: double */
            grossProfit: number | string;
            /** Format: int32 */
            tiedCount: number | string;
        };
        CategoriesResponse: {
            period: components["schemas"]["PeriodDto"];
            items: components["schemas"]["CategoryRow"][];
        };
        CategoryRow: {
            /** Format: uuid */
            categoryId: string;
            name: string;
            /** Format: double */
            revenue: number | string;
            /** Format: double */
            grossProfit: number | string;
            /** Format: double */
            margin: null | number | string;
            /** Format: int32 */
            unitsSold: number | string;
            /** Format: double */
            revenueShare: null | number | string;
        };
        CountMetric: {
            /** Format: int32 */
            current: number | string;
            /** Format: int32 */
            previous: number | string;
            /** Format: double */
            change: null | number | string;
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        KpiResponse: {
            period: components["schemas"]["PeriodDto"];
            previousPeriod: components["schemas"]["PeriodDto"];
            revenue: components["schemas"]["ValueMetric"];
            grossProfit: components["schemas"]["ValueMetric"];
            salesCount: components["schemas"]["CountMetric"];
            averageCheck: components["schemas"]["AverageCheckMetric"];
            margin: components["schemas"]["MarginMetric"];
            refunds: components["schemas"]["RefundsDto"];
            bestManager: null | components["schemas"]["BestManagerDto"];
        };
        MarginMetric: {
            /** Format: double */
            current: null | number | string;
            /** Format: double */
            previous: null | number | string;
            /** Format: double */
            changePoints: null | number | string;
        };
        PeriodDto: {
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        RankingResponse: {
            rankBy: string;
            period: components["schemas"]["PeriodDto"];
            previousPeriod: components["schemas"]["PeriodDto"];
            items: components["schemas"]["RankingRow"][];
        };
        RankingRow: {
            /** Format: int32 */
            rank: null | number | string;
            /** Format: uuid */
            managerId: string;
            firstName: string;
            lastName: string;
            team: string;
            isActive: boolean;
            hasSales: boolean;
            /** Format: int32 */
            salesCount: number | string;
            /** Format: double */
            revenue: number | string;
            /** Format: double */
            grossProfit: number | string;
            /** Format: double */
            averageCheck: null | number | string;
            /** Format: double */
            margin: null | number | string;
            /** Format: double */
            metricChange: null | number | string;
        };
        RecentSaleItemDto: {
            productName: string;
            /** Format: int32 */
            quantity: number | string;
        };
        RecentSaleRow: {
            /** Format: uuid */
            saleId: string;
            /** Format: date-time */
            soldAt: string;
            /** Format: uuid */
            managerId: string;
            managerName: string;
            customerCompany: string;
            status: components["schemas"]["SaleStatus"];
            /** Format: double */
            amount: number | string;
            /** Format: double */
            grossProfit: number | string;
            items: components["schemas"]["RecentSaleItemDto"][];
        };
        RecentSalesResponse: {
            items: components["schemas"]["RecentSaleRow"][];
            nextCursor: null | string;
        };
        RefundsDto: {
            amount: components["schemas"]["ValueMetric"];
            rate: components["schemas"]["MarginMetric"];
        };
        SaleStatus: number;
        TimeseriesPoint: {
            /** Format: date */
            bucketStart: string;
            /** Format: date */
            bucketEnd: string;
            /** Format: double */
            revenue: number | string;
            /** Format: double */
            grossProfit: number | string;
            /** Format: int32 */
            salesCount: number | string;
        };
        TimeseriesResponse: {
            granularity: string;
            period: components["schemas"]["PeriodDto"];
            points: components["schemas"]["TimeseriesPoint"][];
        };
        TopProductRow: {
            /** Format: uuid */
            productId: string;
            sku: string;
            name: string;
            categoryName: string;
            /** Format: double */
            revenue: number | string;
            /** Format: double */
            grossProfit: number | string;
            /** Format: double */
            margin: null | number | string;
            /** Format: int32 */
            unitsSold: number | string;
        };
        TopProductsResponse: {
            period: components["schemas"]["PeriodDto"];
            items: components["schemas"]["TopProductRow"][];
        };
        ValueMetric: {
            /** Format: double */
            current: number | string;
            /** Format: double */
            previous: number | string;
            /** Format: double */
            change: null | number | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetKpis: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetManagerRanking: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                rankBy?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetTimeseries: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeseriesResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetCategories: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriesResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetTopProducts: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopProductsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetRecentSales: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                limit?: number | string;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecentSalesResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
